package com.example.ronanlina.firestoretest;

import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;

import java.util.HashMap;
import java.util.Map;

public class AddActivity extends AppCompatActivity {

    //member vars
    EditText mRestoName;
    EditText mAveragePrice;
    Button mAddInfo;
    FirebaseFirestore db;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add);

        mRestoName = (EditText) findViewById(R.id.addResInput);
        mAveragePrice = (EditText) findViewById(R.id.addAveragePrice);
        mAddInfo = (Button) findViewById(R.id.addResInfoButton);

        db = FirebaseFirestore.getInstance();


        mAddInfo.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                String restoName = mRestoName.getText().toString();
                Double averagePrice = Double.valueOf(mAveragePrice.getText().toString());

                Map<String, Object> resInfo = new HashMap<>();
                resInfo.put("restoname", restoName);
                resInfo.put("aveprice", averagePrice);

                // .set = .collection.document.set = custom uid
                //              table name                 uid          map string object that contains the data to be added
                //db.collection("restaurants").document("10001").set(resInfo); // adding with custom id/document

                //autogenerated document/uid
                db.collection("restaurants")
                        .add(resInfo)
                        .addOnSuccessListener(new OnSuccessListener<DocumentReference>() {
                            @Override
                            public void onSuccess(DocumentReference documentReference) {
                                Toast.makeText(getApplicationContext(),"success",Toast.LENGTH_SHORT).show();
                            }
                        })
                        .addOnFailureListener(new OnFailureListener() {
                            @Override
                            public void onFailure(@NonNull Exception e) {
                                Toast.makeText(getApplicationContext(),"fail",Toast.LENGTH_SHORT).show();
                            }
                        });

            }
        });



    }

 /*   private String generateDocument(){

    }*/
}
